const CONTACT_LIST = [
  {
    id: 1,
    avatar: "/static/avatar/001-man.svg",
    name: "Zachary Gomez",
    company: "Google Inc",
    email: "zachary-gomez@gmail.com",
    position: "Editor",
    phone: "(01) 4563 4556",
  },
  {
    id: 2,
    avatar: "/static/avatar/002-girl.svg",
    name: "Amanda Montgomery",
    company: "Meta",
    email: "montgomery@ya.com",
    position: "Subscriber",
    phone: "(01) 4563 4556",
  },
  {
    id: 3,
    avatar: "/static/avatar/003-boy.svg",
    name: "Lester Holland",
    company: "Amazon",
    email: "lester75@gmail.com",
    position: "Subscriber",
    phone: "(01) 4563 4556",
  },
  {
    id: 4,
    avatar: "/static/avatar/004-woman.svg",
    name: "Max Allison",
    company: "Linkedin",
    email: "max-allison@pochta.io",
    position: "Subscriber",
    phone: "(01) 4563 4556",
  },
  {
    id: 5,
    avatar: "/static/avatar/005-man-1.svg",
    name: "Richard Gregory",
    company: "Alibaba",
    email: "gregory@gmail.com",
    position: "Subscriber",
    phone: "(01) 4563 4556",
  },
  {
    id: 6,
    avatar: "/static/avatar/006-woman-1.svg",
    name: "Clifford Caldwell",
    company: "Disney",
    email: "clifford-c@gmail.com",
    position: "Author",
    phone: "(01) 4563 4556",
  },
  {
    id: 7,
    avatar: "/static/avatar/007-boy-1.svg",
    name: "Lester Holland",
    company: "Squarespace",
    email: "lester75@gmail.com",
    position: "Subscriber",
    phone: "(01) 4563 4556",
  },
  {
    id: 8,
    avatar: "/static/avatar/008-clown.svg",
    name: "Richard Gregory",
    company: "Microsoft",
    email: "gregory@gmail.com",
    position: "Subscriber",
    phone: "(01) 4563 4556",
  },
  {
    id: 9,
    avatar: "/static/avatar/009-firefighter.svg",
    name: "Max Allison",
    company: "Wix",
    email: "max-allison@pochta.io",
    position: "Subscriber",
    phone: "(01) 4563 4556",
  },
  {
    id: 10,
    avatar: "/static/avatar/010-girl-1.svg",
    name: "Zachary Gomez",
    company: "Seek",
    email: "zachary-gomez@gmail.com",
    position: "Editor",
    phone: "(01) 4563 4556",
  },
  {
    id: 11,
    avatar: "/static/avatar/011-man-2.svg",
    name: "Zachary Gomez",
    company: "Ui Lib",
    email: "zachary-gomez@gmail.com",
    position: "Editor",
    phone: "(01) 4563 4556",
  },
  {
    id: 12,
    avatar: "/static/avatar/012-woman-2.svg",
    name: "Zachary Gomez",
    company: "Ui Lib",
    email: "zachary-gomez@gmail.com",
    position: "Editor",
    phone: "(01) 4563 4556",
  },
];

export default CONTACT_LIST;
