const USER_LIST = [
  {
    id: 1,
    avatar: "/static/avatar/001-man.svg",
    name: "Zachary Gomez",
    username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    role: "Editor",
    company: "Ui Lib",
  },
  {
    id: 2,
    avatar: "/static/avatar/002-girl.svg",
    name: "Amanda Montgomery",
    username: "amanda-montgomery",
    email: "montgomery@ya.com",
    role: "Subscriber",
    company: "Facebook",
  },
  {
    id: 3,
    avatar: "/static/avatar/003-boy.svg",
    name: "Lester Holland",
    username: "lester-holland",
    email: "lester75@gmail.com",
    role: "Subscriber",
    company: "Google",
  },
  {
    id: 4,
    avatar: "/static/avatar/004-woman.svg",
    name: "Max Allison",
    username: "max-allison",
    email: "max-allison@pochta.io",
    role: "Subscriber",
    company: "Microsoft",
  },
  {
    id: 5,
    avatar: "/static/avatar/005-man-1.svg",
    name: "Richard Gregory",
    username: "r.gregory",
    email: "gregory@gmail.com",
    role: "Subscriber",
    company: "Amazon",
  },
  {
    id: 6,
    avatar: "/static/avatar/006-woman-1.svg",
    name: "Clifford Caldwell",
    username: "clifford-caldwell",
    email: "clifford-c@gmail.com",
    role: "Author",
    company: "Apple",
  },
  {
    id: 7,
    avatar: "/static/avatar/007-boy-1.svg",
    name: "Lester Holland",
    username: "zlester-holland",
    email: "lester75@gmail.com",
    role: "Subscriber",
    company: "Fiverr",
  },
  {
    id: 8,
    avatar: "/static/avatar/008-clown.svg",
    name: "Richard Gregory",
    username: "r.gregory",
    email: "gregory@gmail.com",
    role: "Subscriber",
    company: "Brain Station",
  },
  {
    id: 9,
    avatar: "/static/avatar/009-firefighter.svg",
    name: "Max Allison",
    username: "max-allison",
    email: "max-allison@pochta.io",
    role: "Subscriber",
    company: "We Devs",
  },
  {
    id: 10,
    avatar: "/static/avatar/010-girl-1.svg",
    name: "Zachary Gomez",
    username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    role: "Editor",
    company: "Ui Lib",
  },
  {
    id: 11,
    avatar: "/static/avatar/011-man-2.svg",
    name: "Zachary Gomez",
    username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    role: "Editor",
    company: "Ui Lib",
  },
  {
    id: 12,
    avatar: "/static/avatar/012-woman-2.svg",
    name: "Zachary Gomez",
    username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    role: "Editor",
    company: "Ui Lib",
  },
];

export default USER_LIST;
